# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winery', '0005_auto_20170217_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='C:/Users/Admin/Desktop/teste/jquerymobile/images/test/company'),
        ),
    ]
