# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winery', '0007_auto_20170219_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='award',
            field=models.ImageField(null=True, upload_to='C:/Users/Admin/Desktop/winerymobile/img/award'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='C:/Users/Admin/Desktop/winerymobile/img/company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='C:/Users/Admin/Desktop/winerymobile/img/product'),
        ),
    ]
