# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winery', '0009_clientuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='city',
            field=models.CharField(default='Tirane', max_length=100),
            preserve_default=False,
        ),
    ]
