# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winery', '0010_clientuser_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winery.ClientUser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winery.Product')),
            ],
        ),
    ]
