# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winery', '0014_auto_20170307_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punonjes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Manager', models.BooleanField(default='False')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winery.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique='True')),
                ('password', models.CharField(max_length=130)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default='True')),
                ('is_employee', models.BooleanField(default='False')),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='punonjes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='winery.Users'),
        ),
    ]
