# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winery', '0016_auto_20170307_0126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employees',
        ),
    ]
