# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winery', '0017_auto_20170307_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winery.Users'),
        ),
    ]
