# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winery', '0018_auto_20170307_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porosi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('sasia', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winery.Users')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winery.Product')),
            ],
        ),
    ]
