# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winery', '0020_auto_20170309_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
